In [ ]:
import tensorflow as tf 

# Create a tensor
a = [[1, 2, 3], [4, 5, 6]]
tensor = tf.constant(a)

# Get the shape of the tensor
shape = tensor.shape

print('Tensor: ', tensor)
print('Tensor shape: ', shape)



c:\Users\E15\PycharmProjects\AI_Level_1_Bat_5\.venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


Tensor:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor shape:  (2, 3)


In [2]:
size = tf.size(tensor)
print("Tensor size: ", size)

Tensor size:  tf.Tensor(6, shape=(), dtype=int32)


In [4]:
import tensorflow as tf
t1 = tf.constant([1, 2, 3, 4, 5, 6, 7])

#a slice from index 1 to 3
s1 = tf.slice(t1, begin=[1], size=[3])
print(s1)
s2 = t1[1:4]

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [9]:
t2 = tf.constant([[0, 1],
                  [3, 4],
                  ])

print(t2[0:2, 0:1])

tf.Tensor(
[[0]
 [3]], shape=(2, 1), dtype=int32)
